### ISSUE TITLE
Cannot connect to X server 

### ISSUE THREAD

**Issue by samar-080301** [ajeetkharel/autodrive#2]
I cloned this repository and tried it in google colab.
I wrote `!python main.py --input /content/Untitled_720p_1.mp4` But the above error occurred.

**Comment by ajeetkharel** [comment]
> I cloned this repository and tried it in google colab.
> I wrote `!python main.py --input /content/Untitled_720p_1.mp4` But the above error occurred.

Since you cannot use the display screen from colab, the imshow function of opencv produces this error. For this you just need to comment out ```cv2.imshow``` part from the main.py and you are good to go.

Comment out line 87, 88, 89 and dont forget to define output path i.e.   ``` --output output_video.mkv```  for you to see the final output in a video.

**Comment by samar-080301** [comment]
Thank You for your response. I'll try it.
